# Generated by Django 5.2.14 on 2026-06-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='Name of the class (e.g., Grade 10).', max_length=50)),
                ('section', models.CharField(help_text='Section identifier (e.g., Section A).', max_length=10)),
                ('room_number', models.CharField(help_text='Physical room number in the school.', max_length=20)),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Assigned class teacher for this classroom.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='teachers.teacher')),
            ],
        ),
    ]
