# Generated by Django 6.0.5 on 2026-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
