# Generated by Django 5.2.14 on 2026-06-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the teacher.', max_length=255)),
                ('email', models.EmailField(help_text='Unique professional email address.', max_length=254, unique=True)),
                ('subject', models.CharField(help_text='Primary subject taught by the teacher.', max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly salary of the teacher.', max_digits=10)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile photo.', null=True, upload_to='teachers/')),
            ],
        ),
    ]
