# Generated by Django 5.2.14 on 2026-06-02 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_product_student_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name or designation of the classroom.', max_length=100)),
                ('teacher', models.ForeignKey(help_text='Select the teacher assigned to this classroom.', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='users.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.classroom'),
        ),
    ]
