# Generated by Django 6.0.5 on 2026-05-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.teacher')),
            ],
        ),
    ]
