# Generated by Django 5.2.14 on 2026-06-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the student.', max_length=255)),
                ('email', models.EmailField(help_text='Unique personal or guardian email address.', max_length=254, unique=True)),
                ('age', models.IntegerField(help_text='Age of the student.')),
                ('roll_number', models.CharField(help_text='Unique roll number assigned to the student.', max_length=50, unique=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture of the student.', null=True, upload_to='students/')),
                ('classroom', models.ForeignKey(blank=True, help_text='The classroom to which the student is assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classrooms.classroom')),
            ],
        ),
    ]
